spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://testfnol.documents.azure.com:443/
        key: ${SPRING_CLOUD_AZURE_COSMOS_KEY}
        database: my-database
  application:
    name: cheese-api

  data:
    mongodb:
      database: players
      uri: ${SPRING_DATA_MONGO_URI}
